// lib/tips.ts
// Tip-of-the-Day data — shared between HomeScreen (legacy) and DiscoverTab (new layout).
// Each level has a pool of tips; one is shown per day based on a date seed.

export interface Tip {
  type: 'word' | 'expression' | 'phrasal verb' | 'idiom';
  term: string;
  meaning: string;
  example: string;
  meaningPt?: string;
  examplePt?: string;
}

export const TIPS: Record<string, Tip[]> = {
  Novice: [
    // ── Words ──
    { type: 'word',        term: 'ambitious',     meaning: 'having a strong desire to succeed',                          example: 'She\'s very ambitious and wants to become a doctor.',           meaningPt: 'ter um forte desejo de ter sucesso',                         examplePt: 'Ela é muito ambiciosa e quer se tornar médica.' },
    { type: 'word',        term: 'grateful',      meaning: 'feeling thankful for something good',                        example: 'I\'m so grateful for your help today.',                         meaningPt: 'sentir-se grato por algo bom',                               examplePt: 'Sou muito grato pela sua ajuda hoje.' },
    { type: 'word',        term: 'hesitate',      meaning: 'to pause before acting, often from doubt',                   example: 'Don\'t hesitate to ask if you have any questions.',             meaningPt: 'pausar antes de agir, geralmente por dúvida',                examplePt: 'Não hesite em perguntar se tiver dúvidas.' },
    { type: 'word',        term: 'fluent',        meaning: 'speaking a language smoothly and naturally',                 example: 'After two years of practice, she became fluent in English.',    meaningPt: 'falar um idioma com fluidez e naturalidade',                 examplePt: 'Após dois anos de prática, ela ficou fluente em inglês.' },
    { type: 'word',        term: 'available',     meaning: 'free to use or accessible at a given time',                  example: 'Is this time slot available for a meeting?',                   meaningPt: 'livre para usar ou acessível em determinado momento',        examplePt: 'Este horário está disponível para uma reunião?' },
    { type: 'word',        term: 'improve',       meaning: 'to get better at something over time',                       example: 'You\'ll improve faster if you practise every day.',             meaningPt: 'melhorar em algo ao longo do tempo',                         examplePt: 'Você vai melhorar mais rápido se praticar todos os dias.' },
    { type: 'word',        term: 'actually',      meaning: 'in reality — often used to correct or add information',      example: 'I thought it was easy, but actually it was quite hard.',        meaningPt: 'na verdade — usado para corrigir ou acrescentar algo',       examplePt: 'Achei que seria fácil, mas na verdade foi bem difícil.' },
    { type: 'word',        term: 'definitely',    meaning: 'without any doubt; certainly',                               example: 'I\'m definitely coming to the party tonight.',                  meaningPt: 'com certeza; definitivamente',                               examplePt: 'Com certeza vou à festa hoje à noite.' },
    { type: 'word',        term: 'although',      meaning: 'in spite of the fact that — like "even though"',             example: 'Although it was raining, we went for a walk.',                  meaningPt: 'embora; apesar de — como "even though"',                    examplePt: 'Embora estivesse chovendo, fomos caminhar.' },
    { type: 'word',        term: 'unless',        meaning: 'except if — used for conditions that prevent something',     example: 'I won\'t go unless you come with me.',                          meaningPt: 'a não ser que — condição que impede algo',                  examplePt: 'Não vou a não ser que você venha comigo.' },
    { type: 'word',        term: 'meanwhile',     meaning: 'at the same time; during that period',                       example: 'She cooked dinner. Meanwhile, he set the table.',               meaningPt: 'enquanto isso; ao mesmo tempo',                              examplePt: 'Ela cozinhou o jantar. Enquanto isso, ele pôs a mesa.' },
    { type: 'word',        term: 'whenever',      meaning: 'every time that; at any time',                               example: 'Whenever I\'m stressed, I go for a run.',                       meaningPt: 'sempre que; toda vez que',                                   examplePt: 'Sempre que estou estressado, vou correr.' },
    { type: 'word',        term: 'however',       meaning: 'on the other hand; despite that',                            example: 'It\'s expensive. However, it\'s worth it.',                     meaningPt: 'porém; no entanto',                                          examplePt: 'É caro. Porém, vale a pena.' },
    { type: 'word',        term: 'therefore',     meaning: 'as a result; for that reason',                               example: 'She studied hard and therefore passed the exam.',               meaningPt: 'portanto; por isso',                                         examplePt: 'Ela estudou muito e portanto passou na prova.' },
    { type: 'word',        term: 'especially',    meaning: 'more than usual; in particular',                             example: 'I love cooking, especially on weekends.',                       meaningPt: 'especialmente; em particular',                               examplePt: 'Adoro cozinhar, especialmente nos fins de semana.' },
    { type: 'word',        term: 'probably',      meaning: 'almost certainly; very likely',                              example: 'It\'s cloudy — it\'s probably going to rain.',                  meaningPt: 'provavelmente; quase certamente',                            examplePt: 'Está nublado — provavelmente vai chover.' },
    { type: 'word',        term: 'suddenly',      meaning: 'quickly and unexpectedly',                                   example: 'Suddenly, the lights went out.',                                meaningPt: 'de repente; subitamente',                                    examplePt: 'De repente, as luzes se apagaram.' },
    { type: 'word',        term: 'recently',      meaning: 'not long ago; in the near past',                             example: 'I recently started learning English.',                          meaningPt: 'recentemente; não faz muito tempo',                          examplePt: 'Comecei a aprender inglês recentemente.' },
    { type: 'word',        term: 'immediately',   meaning: 'at once; without delay',                                     example: 'Call me immediately if anything changes.',                      meaningPt: 'imediatamente; de imediato',                                 examplePt: 'Me ligue imediatamente se algo mudar.' },
    { type: 'word',        term: 'instead',       meaning: 'in place of; as an alternative',                             example: 'I had tea instead of coffee.',                                  meaningPt: 'em vez de; ao invés de',                                    examplePt: 'Tomei chá em vez de café.' },
    { type: 'word',        term: 'during',        meaning: 'throughout or at a point within a time period',              example: 'I fell asleep during the movie.',                               meaningPt: 'durante; ao longo de',                                       examplePt: 'Adormeci durante o filme.' },
    { type: 'word',        term: 'towards',       meaning: 'in the direction of',                                        example: 'She walked towards the door.',                                  meaningPt: 'em direção a; para',                                         examplePt: 'Ela caminhou em direção à porta.' },
    { type: 'word',        term: 'patient',       meaning: 'able to wait calmly without getting frustrated',             example: 'Be patient — learning a language takes time.',                  meaningPt: 'capaz de esperar com calma sem se frustrar',                 examplePt: 'Tenha paciência — aprender um idioma leva tempo.' },
    { type: 'word',        term: 'confident',     meaning: 'feeling certain about your own abilities',                   example: 'She felt confident speaking English at the meeting.',           meaningPt: 'sentir-se seguro quanto às próprias habilidades',            examplePt: 'Ela se sentiu confiante falando inglês na reunião.' },
    { type: 'word',        term: 'obvious',       meaning: 'easy to see or understand; clear',                           example: 'The answer was obvious once she explained it.',                 meaningPt: 'fácil de ver ou entender; claro',                            examplePt: 'A resposta ficou óbvia quando ela explicou.' },
    { type: 'word',        term: 'common',        meaning: 'happening often; found in many places',                      example: '"Get" is one of the most common verbs in English.',             meaningPt: 'que acontece com frequência; encontrado em muitos lugares',  examplePt: '"Get" é um dos verbos mais comuns em inglês.' },
    { type: 'word',        term: 'specific',      meaning: 'clearly defined; exact and detailed',                        example: 'Can you be more specific about what you need?',                 meaningPt: 'claramente definido; exato e detalhado',                     examplePt: 'Você pode ser mais específico sobre o que precisa?' },
    // ── Expressions ──
    { type: 'expression',  term: 'hang on',       meaning: 'wait a moment',                                              example: 'Hang on, I\'ll be right back.',                                 meaningPt: 'espera um momento',                                          examplePt: 'Espera, já volto.' },
    { type: 'expression',  term: 'go ahead',      meaning: 'you can proceed or do something',                            example: 'Go ahead — I\'m listening.',                                   meaningPt: 'você pode prosseguir ou fazer algo',                         examplePt: 'Pode ir — estou ouvindo.' },
    { type: 'expression',  term: 'no wonder',     meaning: 'it\'s not surprising',                                       example: 'No wonder you\'re tired — you worked all day!',                meaningPt: 'não é surpresa',                                             examplePt: 'Não é à toa que você está cansado — trabalhou o dia todo!' },
    { type: 'expression',  term: 'fair enough',   meaning: 'that\'s reasonable or acceptable',                           example: 'A: Can we meet at 3? B: Fair enough, see you then.',            meaningPt: 'isso é razoável ou aceitável',                               examplePt: 'R: Podemos nos encontrar às 3? B: Tudo bem, então.' },
    { type: 'expression',  term: 'of course',     meaning: 'naturally — warmer and more natural than "obviously"',       example: 'Of course I\'ll help you with that.',                           meaningPt: 'naturalmente — mais caloroso do que "obviously"',            examplePt: 'Claro que vou te ajudar com isso.' },
    { type: 'expression',  term: 'never mind',    meaning: 'it doesn\'t matter, forget it',                              example: 'Never mind, I found it myself.',                                meaningPt: 'não importa, esqueça',                                       examplePt: 'Deixa pra lá, eu mesmo encontrei.' },
    { type: 'expression',  term: 'I mean',        meaning: 'used to clarify or rephrase what you just said',             example: 'It was good — I mean, not perfect, but really solid.',          meaningPt: 'quer dizer — usado para esclarecer o que acabou de dizer',  examplePt: 'Foi bom — quer dizer, não perfeito, mas muito sólido.' },
    { type: 'expression',  term: 'you know',      meaning: 'used to check understanding or soften a statement',          example: 'It\'s like, you know, really hard to explain.',                 meaningPt: 'sabe? — usado para verificar compreensão ou suavizar',      examplePt: 'É tipo, sabe, muito difícil de explicar.' },
    { type: 'expression',  term: 'kind of',       meaning: 'somewhat; a little (informal softener)',                     example: 'I\'m kind of tired today — long week.',                         meaningPt: 'meio que; um pouco (suavizador informal)',                   examplePt: 'Estou meio cansado hoje — semana longa.' },
    { type: 'expression',  term: 'sort of',       meaning: 'similar to "kind of" — slightly, in a way',                 example: 'It\'s sort of complicated to explain.',                         meaningPt: 'parecido com "kind of" — de certa forma, um pouco',         examplePt: 'É de certa forma complicado de explicar.' },
    { type: 'expression',  term: 'by the way',    meaning: 'used to introduce a new topic or add a side comment',        example: 'By the way, did you see the news today?',                       meaningPt: 'aliás; a propósito — para introduzir um novo assunto',      examplePt: 'Aliás, você viu as notícias hoje?' },
    { type: 'expression',  term: 'as soon as',    meaning: 'immediately when; the moment that',                          example: 'Call me as soon as you arrive.',                                meaningPt: 'assim que; tão logo',                                        examplePt: 'Me ligue assim que chegar.' },
    { type: 'expression',  term: 'in fact',       meaning: 'used to add emphasis or introduce real information',         example: 'It was great. In fact, it was the best trip of my life.',       meaningPt: 'na verdade; de fato — para enfatizar ou acrescentar',       examplePt: 'Foi ótimo. De fato, foi a melhor viagem da minha vida.' },
    { type: 'expression',  term: 'at least',      meaning: 'not less than; used to find a positive in a bad situation',  example: 'The hotel wasn\'t great, but at least it was clean.',           meaningPt: 'pelo menos; ao menos',                                       examplePt: 'O hotel não era ótimo, mas pelo menos estava limpo.' },
    { type: 'expression',  term: 'as well',       meaning: 'in addition; too (used at the end of a sentence)',           example: 'She speaks French and German as well.',                         meaningPt: 'também; além disso (no final da frase)',                     examplePt: 'Ela fala francês e alemão também.' },
    { type: 'expression',  term: 'I see',         meaning: 'showing you understand or have just realised something',     example: 'I see — so the meeting was moved to Thursday?',                 meaningPt: 'entendo; ah, entendi — mostra que você compreendeu',         examplePt: 'Entendo — então a reunião foi movida para quinta?' },
    { type: 'expression',  term: 'more or less',  meaning: 'approximately; roughly',                                     example: 'It takes more or less an hour to get there by train.',          meaningPt: 'mais ou menos; aproximadamente',                             examplePt: 'Leva mais ou menos uma hora para chegar de trem.' },
    { type: 'expression',  term: 'take it easy',  meaning: 'relax; don\'t worry; slow down',                             example: 'Take it easy — there\'s no rush, we have plenty of time.',      meaningPt: 'relaxa; não se preocupa; vai com calma',                    examplePt: 'Vai com calma — não há pressa, temos bastante tempo.' },
    // ── Phrasal verbs ──
    { type: 'phrasal verb', term: 'give up',      meaning: 'to stop trying; to quit',                                    example: 'Don\'t give up — you\'re so close to finishing!',               meaningPt: 'desistir; parar de tentar',                                  examplePt: 'Não desista — você está tão perto de terminar!' },
    { type: 'phrasal verb', term: 'look up',      meaning: 'to search for information in a book or online',              example: 'I always look up new words in the dictionary.',                 meaningPt: 'procurar uma informação num livro ou online',                examplePt: 'Sempre procuro palavras novas no dicionário.' },
    { type: 'phrasal verb', term: 'show up',      meaning: 'to arrive somewhere; to appear',                             example: 'He didn\'t show up to the meeting — no one knows why.',         meaningPt: 'aparecer em algum lugar; chegar',                            examplePt: 'Ele não apareceu na reunião — ninguém sabe por quê.' },
    { type: 'phrasal verb', term: 'pick up',      meaning: 'to learn something informally; to collect something',        example: 'I picked up a lot of English just by watching series.',         meaningPt: 'aprender algo de forma informal; pegar algo',                examplePt: 'Aprendi muito inglês só assistindo a séries.' },
    { type: 'phrasal verb', term: 'find out',     meaning: 'to discover or learn new information',                       example: 'I just found out the exam is tomorrow — not next week.',        meaningPt: 'descobrir ou aprender uma informação nova',                  examplePt: 'Descobri que a prova é amanhã — não na semana que vem.' },
    { type: 'phrasal verb', term: 'wake up',      meaning: 'to stop sleeping; to become aware',                          example: 'I wake up at 7 every day, even on weekends.',                   meaningPt: 'acordar; parar de dormir',                                   examplePt: 'Acordo às 7 todos os dias, até nos fins de semana.' },
    // ── Idioms ──
    { type: 'idiom',        term: 'break the ice',  meaning: 'start a conversation in a social situation',               example: 'He told a joke to break the ice at the meeting.',               meaningPt: 'iniciar uma conversa em uma situação social',                examplePt: 'Ele contou uma piada para quebrar o gelo na reunião.' },
    { type: 'idiom',        term: 'piece of cake',  meaning: 'something very easy to do',                                example: 'The test was a piece of cake — I finished in 10 minutes.',      meaningPt: 'algo muito fácil de fazer',                                  examplePt: 'A prova foi moleza — terminei em 10 minutos.' },
    { type: 'idiom',        term: 'under the weather', meaning: 'feeling slightly ill or unwell',                        example: 'I\'m feeling a bit under the weather — I might stay home.',      meaningPt: 'sentindo-se um pouco mal ou indisposto',                    examplePt: 'Estou me sentindo um pouco mal — talvez fique em casa.' },
    { type: 'idiom',        term: 'on the tip of my tongue', meaning: 'you almost remember something but can\'t quite', example: 'His name is on the tip of my tongue — I just can\'t get it.',   meaningPt: 'quase lembro de algo, mas não consigo',                     examplePt: 'O nome dele está na ponta da língua — não consigo lembrar.' },
    { type: 'idiom',        term: 'better late than never', meaning: 'it\'s better to do something late than not at all', example: 'You finally finished the course — better late than never!',   meaningPt: 'melhor tarde do que nunca',                                  examplePt: 'Você finalmente terminou o curso — melhor tarde do que nunca!' },
    { type: 'idiom',        term: 'bite off more than you can chew', meaning: 'take on more than you can handle',       example: 'Don\'t bite off more than you can chew with all those classes.', meaningPt: 'assumir mais do que você consegue lidar',                  examplePt: 'Não assuma mais do que consegue com tantas aulas.' },
    { type: 'idiom',        term: 'cost an arm and a leg', meaning: 'to be very expensive',                              example: 'That new phone costs an arm and a leg.',                        meaningPt: 'custar muito caro; custar os olhos da cara',                 examplePt: 'Aquele celular novo custa os olhos da cara.' },
    { type: 'idiom',        term: 'hit the sack',   meaning: 'to go to bed; to go to sleep',                             example: 'I\'m exhausted — I\'m going to hit the sack early tonight.',   meaningPt: 'ir dormir; ir para a cama',                                  examplePt: 'Estou exausto — vou dormir cedo hoje à noite.' },
    { type: 'idiom',        term: 'once in a while', meaning: 'occasionally; sometimes but not often',                   example: 'I don\'t eat junk food often — only once in a while.',          meaningPt: 'de vez em quando; às vezes, mas não com frequência',        examplePt: 'Não como junk food sempre — só de vez em quando.' },
  ],
  Inter: [
    // ── Phrasal verbs ──
    { type: 'phrasal verb', term: 'bring up',      meaning: 'to mention a topic in conversation',                        example: 'She brought up the salary issue during the meeting.' },
    { type: 'phrasal verb', term: 'put off',       meaning: 'to postpone or delay something',                            example: 'Stop putting off your homework — do it now.' },
    { type: 'phrasal verb', term: 'run into',      meaning: 'to meet someone unexpectedly',                              example: 'I ran into my old teacher at the supermarket.' },
    { type: 'phrasal verb', term: 'give away',     meaning: 'to reveal information unintentionally',                     example: 'His nervous laugh gave away that he was lying.' },
    { type: 'phrasal verb', term: 'look into',     meaning: 'to investigate or research something',                      example: 'I\'ll look into the problem and get back to you.' },
    { type: 'phrasal verb', term: 'take on',       meaning: 'to accept a challenge or responsibility',                   example: 'She decided to take on the new project.' },
    { type: 'phrasal verb', term: 'come across',   meaning: 'to seem a certain way, or find something by chance',        example: 'He came across as very confident in the interview.' },
    { type: 'phrasal verb', term: 'figure out',    meaning: 'to understand or solve something',                          example: 'I couldn\'t figure out how to fix the error.' },
    { type: 'phrasal verb', term: 'turn down',     meaning: 'to reject an offer or request',                             example: 'She turned down the job offer — the salary was too low.' },
    { type: 'phrasal verb', term: 'catch up',      meaning: 'to reach the same level as others; to update someone',      example: 'I need to catch up on the emails I missed this week.' },
    { type: 'phrasal verb', term: 'back up',       meaning: 'to support someone; to save a copy of data',                example: 'Can you back me up in the meeting? And back up your files!' },
    { type: 'phrasal verb', term: 'carry out',     meaning: 'to complete or perform a task or plan',                     example: 'The team carried out the project on time and under budget.' },
    { type: 'phrasal verb', term: 'set up',        meaning: 'to establish, arrange, or prepare something',               example: 'She set up a new business after leaving her old job.' },
    { type: 'phrasal verb', term: 'deal with',     meaning: 'to handle or manage a situation or problem',                example: 'How do you deal with difficult clients at work?' },
    { type: 'phrasal verb', term: 'point out',     meaning: 'to draw attention to something; to mention',                example: 'He pointed out several errors in my presentation.' },
    { type: 'phrasal verb', term: 'fall apart',    meaning: 'to break into pieces; to fall into disorder',               example: 'The project started to fall apart after the manager left.' },
    { type: 'phrasal verb', term: 'go through',    meaning: 'to experience something; to examine carefully',             example: 'Let\'s go through the report together before the meeting.' },
    { type: 'phrasal verb', term: 'break down',    meaning: 'to stop working; to lose emotional control',                example: 'The car broke down on the motorway. She broke down in tears.' },
    { type: 'phrasal verb', term: 'hold on',       meaning: 'to wait; to grip something tightly',                        example: 'Hold on — I just need to check one thing.' },
    { type: 'phrasal verb', term: 'wrap up',       meaning: 'to finish or conclude something',                           example: 'Let\'s wrap up the meeting — we\'re running out of time.' },
    { type: 'phrasal verb', term: 'take up',       meaning: 'to begin a new hobby or activity',                          example: 'She took up running after the lockdown and never stopped.' },
    { type: 'phrasal verb', term: 'bring about',   meaning: 'to cause something to happen',                              example: 'The new policy brought about significant changes in the team.' },
    { type: 'phrasal verb', term: 'draw on',       meaning: 'to use experience or knowledge as a resource',              example: 'She drew on ten years of teaching experience for her talk.' },
    { type: 'phrasal verb', term: 'cut back on',   meaning: 'to reduce the amount of something',                         example: 'The company cut back on travel expenses to reduce costs.' },
    // ── Idioms ──
    { type: 'idiom',        term: 'hit the nail on the head', meaning: 'to describe something exactly right',            example: 'That\'s exactly it — you really hit the nail on the head.' },
    { type: 'idiom',        term: 'bite the bullet',  meaning: 'to endure a painful situation bravely',                  example: 'I bit the bullet and went to the dentist.' },
    { type: 'idiom',        term: 'on the fence',     meaning: 'undecided about something',                              example: 'I\'m still on the fence about moving to a new city.' },
    { type: 'idiom',        term: 'cost an arm and a leg', meaning: 'to be very expensive',                              example: 'That renovation is going to cost an arm and a leg.' },
    { type: 'idiom',        term: 'get the hang of it', meaning: 'to gradually learn how to do something well',          example: 'Keep practising — you\'ll get the hang of it soon.' },
    { type: 'idiom',        term: 'the ball is in your court', meaning: 'it\'s your turn to take action or decide',     example: 'I\'ve made my offer. The ball is in your court now.' },
    { type: 'idiom',        term: 'the last straw',   meaning: 'the final problem that makes a situation unbearable',    example: 'Being late again was the last straw — she quit immediately.' },
    { type: 'idiom',        term: 'beat around the bush', meaning: 'to avoid talking about the main point directly',    example: 'Stop beating around the bush and tell me what happened.' },
    { type: 'idiom',        term: 'once in a blue moon', meaning: 'very rarely; almost never',                           example: 'I only eat fast food once in a blue moon.' },
    { type: 'idiom',        term: 'pull someone\'s leg', meaning: 'to tease or joke with someone',                       example: 'A: You won the lottery! B: Are you pulling my leg?' },
    { type: 'idiom',        term: 'see eye to eye',   meaning: 'to agree with someone on something',                     example: 'We don\'t always see eye to eye, but we respect each other.' },
    { type: 'idiom',        term: 'ring a bell',      meaning: 'to sound familiar; to remind you of something',          example: 'That name rings a bell — did we meet at the conference?' },
    { type: 'idiom',        term: 'a blessing in disguise', meaning: 'something that seems bad but is actually good',   example: 'Losing that job was a blessing in disguise — I found a better one.' },
    { type: 'idiom',        term: 'get cold feet',    meaning: 'to suddenly feel nervous about doing something',         example: 'She got cold feet before the presentation but nailed it anyway.' },
    { type: 'idiom',        term: 'back to square one', meaning: 'having to start again from the beginning',            example: 'The client rejected everything — we\'re back to square one.' },
    // ── Expressions ──
    { type: 'expression',   term: 'to be honest',     meaning: 'used before a frank or direct opinion',                  example: 'To be honest, I don\'t think that plan will work.' },
    { type: 'expression',   term: 'as far as I know', meaning: 'based on what I know — with some uncertainty',           example: 'As far as I know, the meeting is still on for Friday.' },
    { type: 'expression',   term: 'let alone',        meaning: 'not to mention — for increasingly unlikely things',      example: 'I can barely afford rent, let alone a holiday.' },
    { type: 'expression',   term: 'in a nutshell',    meaning: 'in brief; summarising the key point',                    example: 'In a nutshell, the project is over budget and behind schedule.' },
    { type: 'expression',   term: 'easier said than done', meaning: 'something sounds simple but is actually difficult', example: '"Just relax." — Easier said than done when you\'re under pressure.' },
    { type: 'expression',   term: 'for what it\'s worth', meaning: 'used before an opinion that may or may not be useful', example: 'For what it\'s worth, I think you made the right call.' },
    { type: 'expression',   term: 'on second thought', meaning: 'after reconsidering something',                         example: 'On second thought, let\'s postpone the meeting to Friday.' },
    { type: 'expression',   term: 'that said',        meaning: 'however; in contrast to what was just said',             example: 'The report is long. That said, it covers everything we need.' },
    { type: 'expression',   term: 'as it turns out',  meaning: 'used to introduce a surprising or unexpected result',    example: 'As it turns out, the cheapest option was also the best.' },
    // ── Words ──
    { type: 'word',         term: 'ambiguous',        meaning: 'open to more than one interpretation; unclear',          example: 'His answer was ambiguous — I wasn\'t sure what he meant.' },
    { type: 'word',         term: 'elaborate',        meaning: 'to explain or describe something in more detail',        example: 'Could you elaborate on that point? I\'d like to know more.' },
    { type: 'word',         term: 'compelling',       meaning: 'convincing and interesting; difficult to ignore',        example: 'She made a compelling argument for changing the strategy.' },
    { type: 'word',         term: 'subtle',           meaning: 'not obvious; delicate and hard to notice',               example: 'There\'s a subtle difference between "affect" and "effect".' },
    { type: 'word',         term: 'concise',          meaning: 'giving a lot of information clearly and in few words',   example: 'Keep your email concise — no one reads long messages.' },
    { type: 'word',         term: 'assertive',        meaning: 'confident and direct in expressing opinions',            example: 'You need to be more assertive in meetings — speak up!' },
    { type: 'word',         term: 'prevalent',        meaning: 'widespread; very common in a place or time',             example: 'Remote work is now prevalent across most industries.' },
    { type: 'word',         term: 'tentative',        meaning: 'uncertain; not final or definite',                       example: 'We have a tentative plan, but nothing is confirmed yet.' },
    { type: 'word',         term: 'versatile',        meaning: 'able to adapt to many situations or uses',               example: 'She\'s a versatile writer — she does fiction, essays, and scripts.' },
  ],
  Advanced: [
    // ── Words ──
    { type: 'word',         term: 'albeit',           meaning: 'even though — used for concession mid-sentence',         example: 'It was a successful event, albeit a small one.' },
    { type: 'word',         term: 'concede',          meaning: 'to admit something is true, often reluctantly',          example: 'I have to concede that you make a valid point.' },
    { type: 'word',         term: 'nuance',           meaning: 'a subtle difference in meaning, tone, or expression',    example: 'There\'s a nuance between "confident" and "arrogant".' },
    { type: 'word',         term: 'mitigate',         meaning: 'to reduce the severity or impact of something',          example: 'Good preparation can mitigate the risk of failure.' },
    { type: 'word',         term: 'candid',           meaning: 'truthful and straightforward',                           example: 'Can I give you a candid opinion? I think you need more practice.' },
    { type: 'word',         term: 'pragmatic',        meaning: 'dealing with things sensibly and realistically',         example: 'Let\'s be pragmatic — we don\'t have the budget for that.' },
    { type: 'word',         term: 'eloquent',         meaning: 'expressing ideas clearly and effectively in speech or writing', example: 'Her eloquent defence of the proposal won over the board.' },
    { type: 'word',         term: 'lucid',            meaning: 'easy to understand; clear and rational',                 example: 'Despite the complexity, his explanation was remarkably lucid.' },
    { type: 'word',         term: 'unequivocal',      meaning: 'leaving no doubt; completely clear',                     example: 'The CEO gave an unequivocal statement: there will be no layoffs.' },
    { type: 'word',         term: 'reticent',         meaning: 'not revealing one\'s thoughts or feelings readily',      example: 'He was reticent about his plans — no one knew what he was thinking.' },
    { type: 'word',         term: 'ostensibly',       meaning: 'apparently or on the surface — but possibly not really', example: 'The meeting was ostensibly about budget, but the real issue was leadership.' },
    { type: 'word',         term: 'prerogative',      meaning: 'an exclusive right or privilege',                        example: 'It\'s entirely your prerogative to decline the offer.' },
    { type: 'word',         term: 'pervasive',        meaning: 'spreading widely throughout; present everywhere',        example: 'There\'s a pervasive sense of uncertainty in the market right now.' },
    { type: 'word',         term: 'delineate',        meaning: 'to describe or portray something precisely',             example: 'The report delineates the key risks facing the organisation.' },
    { type: 'word',         term: 'commensurate',     meaning: 'corresponding in size or degree; proportionate',         example: 'The salary should be commensurate with experience and qualifications.' },
    { type: 'word',         term: 'amalgamate',       meaning: 'to combine or unite different things into one',          example: 'The two departments were amalgamated to reduce overhead costs.' },
    { type: 'word',         term: 'circumvent',       meaning: 'to find a way around an obstacle or rule',               example: 'They tried to circumvent the policy, but the board refused.' },
    { type: 'word',         term: 'exacerbate',       meaning: 'to make a problem or bad situation worse',               example: 'The lack of sleep only exacerbated her anxiety before the talk.' },
    { type: 'word',         term: 'tenacious',        meaning: 'determined; refusing to give up easily',                 example: 'He\'s a tenacious negotiator — he never walks away empty-handed.' },
    { type: 'word',         term: 'succinct',         meaning: 'expressed briefly and clearly; to the point',            example: 'Her succinct summary saved everyone thirty minutes of reading.' },
    { type: 'word',         term: 'paradoxical',      meaning: 'seemingly contradictory but possibly true or well-founded', example: 'It\'s paradoxical — the busier I am, the more I seem to get done.' },
    // ── Idioms ──
    { type: 'idiom',        term: 'read between the lines', meaning: 'to understand the hidden or implied meaning',      example: 'Read between the lines — she said "fine" but she\'s not happy.' },
    { type: 'idiom',        term: 'burn bridges',     meaning: 'to permanently damage a relationship or opportunity',    example: 'Don\'t burn bridges with your old employer — you may need them.' },
    { type: 'idiom',        term: 'the tip of the iceberg', meaning: 'a small visible part of a much larger problem',   example: 'The complaints we heard are just the tip of the iceberg.' },
    { type: 'idiom',        term: 'take with a grain of salt', meaning: 'to be skeptical about something you\'ve heard', example: 'Take those reviews with a grain of salt — they may be fake.' },
    { type: 'idiom',        term: 'devil\'s advocate', meaning: 'arguing the opposite side to explore all angles',       example: 'Let me play devil\'s advocate — what if the opposite is true?' },
    { type: 'idiom',        term: 'push the envelope', meaning: 'to go beyond accepted limits; try something new',       example: 'This design really pushes the envelope in modern architecture.' },
    { type: 'idiom',        term: 'a double-edged sword', meaning: 'something with both advantages and disadvantages',   example: 'Social media is a double-edged sword — great for reach, risky for reputation.' },
    { type: 'idiom',        term: 'split hairs',      meaning: 'to make overly fine distinctions; argue about details',  example: 'We\'re splitting hairs here — both options are essentially the same.' },
    { type: 'idiom',        term: 'throw in the towel', meaning: 'to admit defeat; to give up',                          example: 'After three failed attempts, he finally threw in the towel.' },
    { type: 'idiom',        term: 'cut corners',      meaning: 'to do something poorly to save time or money',           example: 'Cutting corners on safety is never acceptable in this industry.' },
    { type: 'idiom',        term: 'on thin ice',      meaning: 'in a risky or precarious situation',                     example: 'After that comment, he\'s on very thin ice with his manager.' },
    { type: 'idiom',        term: 'go to great lengths', meaning: 'to make a big effort to achieve something',           example: 'She went to great lengths to ensure the client was satisfied.' },
    { type: 'idiom',        term: 'hold your ground', meaning: 'to maintain your position under pressure',               example: 'Negotiations were tough, but she held her ground throughout.' },
    { type: 'idiom',        term: 'in the same boat', meaning: 'in the same difficult situation as someone else',        example: 'We\'re all in the same boat here — none of us knows what\'s coming.' },
    { type: 'idiom',        term: 'wear many hats',   meaning: 'to have many different roles or responsibilities',       example: 'In a startup you wear many hats — today I\'m designer, tomorrow I\'m HR.' },
    { type: 'idiom',        term: 'move the goalposts', meaning: 'to change the rules or expectations unfairly',        example: 'Every time we meet the target, they move the goalposts.' },
    // ── Expressions ──
    { type: 'expression',   term: 'by the same token', meaning: 'for the same reason / in the same way',               example: 'He\'s talented, but by the same token, so are the other candidates.' },
    { type: 'expression',   term: 'to put it bluntly', meaning: 'to say something directly, even if it\'s harsh',       example: 'To put it bluntly, your report needs a complete rewrite.' },
    { type: 'expression',   term: 'needless to say',  meaning: 'it should be obvious — use sparingly to avoid arrogance', example: 'Needless to say, we were all shocked by the news.' },
    { type: 'expression',   term: 'all things considered', meaning: 'taking everything into account; overall',          example: 'All things considered, I think the project went quite well.' },
    { type: 'expression',   term: 'with that in mind', meaning: 'taking the previous point into consideration',         example: 'The data is inconclusive. With that in mind, I\'d recommend caution.' },
    { type: 'expression',   term: 'on the face of it', meaning: 'based on initial appearances; superficially',         example: 'On the face of it, the proposal looks attractive. But read the small print.' },
    { type: 'expression',   term: 'it goes without saying', meaning: 'something is so obvious it barely needs to be stated', example: 'It goes without saying that confidentiality is essential here.' },
    { type: 'expression',   term: 'in the final analysis', meaning: 'when everything has been considered; ultimately',  example: 'In the final analysis, the project failed due to poor communication.' },
    { type: 'expression',   term: 'to no avail',      meaning: 'without success; despite efforts',                      example: 'She tried to reach him several times, but to no avail.' },
    { type: 'expression',   term: 'strike a balance', meaning: 'to find an acceptable middle point between extremes',   example: 'The policy tries to strike a balance between security and privacy.' },
    { type: 'expression',   term: 'lend weight to',   meaning: 'to add support or credibility to an argument',          example: 'This new evidence lends weight to the prosecution\'s case.' },
    { type: 'expression',   term: 'read the room',    meaning: 'to understand the mood or feelings of the people around you', example: 'He kept making jokes — he clearly couldn\'t read the room.' },
    { type: 'expression',   term: 'at face value',    meaning: 'accepting something as it appears without questioning deeper', example: 'Don\'t take his offer at face value — read the contract first.' },
    // ── Phrasal verbs ──
    { type: 'phrasal verb', term: 'gloss over',       meaning: 'to treat something briefly without proper attention',   example: 'The report glosses over some serious financial problems.' },
    { type: 'phrasal verb', term: 'call into question', meaning: 'to cause doubt about something',                      example: 'The new findings call into question the entire research methodology.' },
    { type: 'phrasal verb', term: 'bear out',         meaning: 'to confirm or support the truth of something',          example: 'The results bear out the hypothesis we proposed last year.' },
    { type: 'phrasal verb', term: 'give rise to',     meaning: 'to cause or produce something',                         example: 'The merger gave rise to serious concerns about market competition.' },
    { type: 'phrasal verb', term: 'flesh out',        meaning: 'to add more detail or substance to an idea or plan',    example: 'The concept is good — let\'s flesh it out before the next meeting.' },
    { type: 'phrasal verb', term: 'narrow down',      meaning: 'to reduce a list of options to the most likely',        example: 'We\'ve narrowed down the candidates to three finalists.' },
    { type: 'phrasal verb', term: 'iron out',         meaning: 'to resolve difficulties or small problems',             example: 'There are a few details to iron out before we can sign the contract.' },
  ],
};

export const TIP_STYLE: Record<string, { bg: string; color: string }> = {
  'word':         { bg: '#F0FFD9', color: '#3D8800' },
  'expression':   { bg: '#EFF6FF', color: '#1D4ED8' },
  'phrasal verb': { bg: '#FDF2F8', color: '#BE185D' },
  'idiom':        { bg: '#F5F3FF', color: '#6D28D9' },
};

export function getTip(level: string, seed: number): Tip {
  const pool = TIPS[level] ?? TIPS.Novice;
  return pool[seed % pool.length];
}
