// AUTO-GENERATED by scripts/compile-curriculum-v2.mjs — DO NOT EDIT MANUALLY.
// Regenerated on every `node scripts/compile-curriculum-v2.mjs` run based on
// compiled JSON files. To add a module: write the markdown, run compile, and
// this file picks it up automatically.

import type { Level, Module } from './types';

const MODULES: Record<Level, Record<string, () => Module>> = {
  Novice: {
    M01: () => require('@/data/curriculum-v2/novice/M01.json') as Module,
    M02: () => require('@/data/curriculum-v2/novice/M02.json') as Module,
    M03: () => require('@/data/curriculum-v2/novice/M03.json') as Module,
    M04: () => require('@/data/curriculum-v2/novice/M04.json') as Module,
    M05: () => require('@/data/curriculum-v2/novice/M05.json') as Module,
    M06: () => require('@/data/curriculum-v2/novice/M06.json') as Module,
    M07: () => require('@/data/curriculum-v2/novice/M07.json') as Module,
    M08: () => require('@/data/curriculum-v2/novice/M08.json') as Module,
    M09: () => require('@/data/curriculum-v2/novice/M09.json') as Module,
    M10: () => require('@/data/curriculum-v2/novice/M10.json') as Module,
    M11: () => require('@/data/curriculum-v2/novice/M11.json') as Module,
    M12: () => require('@/data/curriculum-v2/novice/M12.json') as Module,
    M13: () => require('@/data/curriculum-v2/novice/M13.json') as Module,
    M14: () => require('@/data/curriculum-v2/novice/M14.json') as Module,
    M15: () => require('@/data/curriculum-v2/novice/M15.json') as Module,
    M16: () => require('@/data/curriculum-v2/novice/M16.json') as Module,
    M17: () => require('@/data/curriculum-v2/novice/M17.json') as Module,
    M18: () => require('@/data/curriculum-v2/novice/M18.json') as Module,
    M19: () => require('@/data/curriculum-v2/novice/M19.json') as Module,
    M20: () => require('@/data/curriculum-v2/novice/M20.json') as Module,
    M21: () => require('@/data/curriculum-v2/novice/M21.json') as Module,
    M22: () => require('@/data/curriculum-v2/novice/M22.json') as Module,
  },
  Inter: {
    M01: () => require('@/data/curriculum-v2/inter/M01.json') as Module,
    M02: () => require('@/data/curriculum-v2/inter/M02.json') as Module,
    M03: () => require('@/data/curriculum-v2/inter/M03.json') as Module,
    M04: () => require('@/data/curriculum-v2/inter/M04.json') as Module,
    M05: () => require('@/data/curriculum-v2/inter/M05.json') as Module,
    M06: () => require('@/data/curriculum-v2/inter/M06.json') as Module,
    M07: () => require('@/data/curriculum-v2/inter/M07.json') as Module,
    M08: () => require('@/data/curriculum-v2/inter/M08.json') as Module,
    M09: () => require('@/data/curriculum-v2/inter/M09.json') as Module,
    M10: () => require('@/data/curriculum-v2/inter/M10.json') as Module,
    M11: () => require('@/data/curriculum-v2/inter/M11.json') as Module,
    M12: () => require('@/data/curriculum-v2/inter/M12.json') as Module,
    M13: () => require('@/data/curriculum-v2/inter/M13.json') as Module,
    M14: () => require('@/data/curriculum-v2/inter/M14.json') as Module,
    M15: () => require('@/data/curriculum-v2/inter/M15.json') as Module,
    M16: () => require('@/data/curriculum-v2/inter/M16.json') as Module,
    M17: () => require('@/data/curriculum-v2/inter/M17.json') as Module,
    M18: () => require('@/data/curriculum-v2/inter/M18.json') as Module,
    M19: () => require('@/data/curriculum-v2/inter/M19.json') as Module,
    M20: () => require('@/data/curriculum-v2/inter/M20.json') as Module,
    M21: () => require('@/data/curriculum-v2/inter/M21.json') as Module,
    M22: () => require('@/data/curriculum-v2/inter/M22.json') as Module,
  },
  Advanced: {
    M01: () => require('@/data/curriculum-v2/advanced/M01.json') as Module,
    M02: () => require('@/data/curriculum-v2/advanced/M02.json') as Module,
    M03: () => require('@/data/curriculum-v2/advanced/M03.json') as Module,
    M04: () => require('@/data/curriculum-v2/advanced/M04.json') as Module,
    M05: () => require('@/data/curriculum-v2/advanced/M05.json') as Module,
    M06: () => require('@/data/curriculum-v2/advanced/M06.json') as Module,
    M07: () => require('@/data/curriculum-v2/advanced/M07.json') as Module,
    M08: () => require('@/data/curriculum-v2/advanced/M08.json') as Module,
    M09: () => require('@/data/curriculum-v2/advanced/M09.json') as Module,
    M10: () => require('@/data/curriculum-v2/advanced/M10.json') as Module,
    M11: () => require('@/data/curriculum-v2/advanced/M11.json') as Module,
  },
};

export function getModule(level: Level, moduleId: string): Module | null {
  const fn = MODULES[level]?.[moduleId];
  return fn ? fn() : null;
}

export function listModules(level: Level): Module[] {
  const bucket = MODULES[level];
  if (!bucket) return [];
  return Object.keys(bucket).sort().map(id => bucket[id]());
}

export function hasModule(level: Level, moduleId: string): boolean {
  return !!MODULES[level]?.[moduleId];
}

export function listModuleSummaries(level: Level): Array<{
  id: string;
  title: string;
  units_count: number;
}> {
  return listModules(level).map(m => ({
    id: m.id,
    title: m.title,
    units_count: m.units.length,
  }));
}
