// AUTO-GENERATED by scripts/compile-curriculum-v2.mjs — DO NOT EDIT MANUALLY.
// Regenerated on every `node scripts/compile-curriculum-v2.mjs` run based on
// compiled JSON files. To add a module: write the markdown, run compile, and
// this file picks it up automatically.

import type { Level, Module } from './types';

const MODULES: Record<Level, Record<string, () => Module>> = {
  Novice: {
    M01: () => require('@/data/curriculum-v2/novice/M01.json') as Module,
    M02: () => require('@/data/curriculum-v2/novice/M02.json') as Module,
    M03: () => require('@/data/curriculum-v2/novice/M03.json') as Module,
    M04: () => require('@/data/curriculum-v2/novice/M04.json') as Module,
  },
  Inter: {},
  Advanced: {},
};

export function getModule(level: Level, moduleId: string): Module | null {
  const fn = MODULES[level]?.[moduleId];
  return fn ? fn() : null;
}

export function listModules(level: Level): Module[] {
  const bucket = MODULES[level];
  if (!bucket) return [];
  return Object.keys(bucket).sort().map(id => bucket[id]());
}

export function hasModule(level: Level, moduleId: string): boolean {
  return !!MODULES[level]?.[moduleId];
}

export function listModuleSummaries(level: Level): Array<{
  id: string;
  title: string;
  units_count: number;
}> {
  return listModules(level).map(m => ({
    id: m.id,
    title: m.title,
    units_count: m.units.length,
  }));
}
